/*
 * generated by Xtext 2.16.0
 */
package compilador.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPascalScopeProvider extends DelegatingScopeProvider {
}
