/**
 * generated by Xtext 2.15.0
 */
package compilador.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import compilador.PascalRuntimeModule;
import compilador.PascalStandaloneSetup;
import compilador.ide.PascalIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PascalIdeSetup extends PascalStandaloneSetup {
  @Override
  public Injector createInjector() {
    PascalRuntimeModule _pascalRuntimeModule = new PascalRuntimeModule();
    PascalIdeModule _pascalIdeModule = new PascalIdeModule();
    return Guice.createInjector(Modules2.mixin(_pascalRuntimeModule, _pascalIdeModule));
  }
}
