/*
 * generated by Xtext 2.15.0
 */
package compilador.validation

import org.eclipse.xtext.validation.Check
import compilador.pascal.caseStatement;
import compilador.pascal.*;

import java.util.HashMap
import java.util.Map
import compilador.pascal.structuredType
import compilador.pascal.pointerType
import compilador.pascal.identifier
import compilador.pascal.recordType
import java.util.HashSet
import compilador.pascal.typeDefinition

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class PascalValidator extends AbstractPascalValidator {

	var variaveisDeclaradas = new HashMap<String, identifier>();
	var variaveisTipo = new HashMap<String, String>();
	var tiposCriados = new HashSet<String>();

	@Check
	def restart(program init) {
		variaveisDeclaradas.clear();
		variaveisTipo.clear();
		tiposCriados.clear();
	}

	/* -------------------- block ----------------------  */
	/* -------------------- block -> typeDefinitionPart ----------------------  */
	@Check
	def checkDefinicoesTipo(typeDefinitionPart deftype) {
		if (deftype.typeDefinition !== null) {
			checkDefTipo(deftype.typeDefinition);
		}
		var definicoes = deftype.typeDefinition1;
		if (!definicoes.isNullOrEmpty()) {
			for (typeDefinition defPart : definicoes) {
				checkDefTipo(defPart);
			}
		}

	}

	def checkDefTipo(typeDefinition definition) {
		var tipoCriado = definition.identifier.identifier;
		if (tiposCriados.contains(tipoCriado)) {
			error("um tipo ja foi criado com id " + tipoCriado, null);
		} else {
			tiposCriados.add(tipoCriado);
		}
	}

	/* -------------------- block -> variableDeclarationPart ----------------------  */
	/**
	 * variableDeclaration: Podemos declarar mais de uma variavel usando apenas uma palavra chave 'var',
	 *  Ex: var nome1, nome2...
	 *  Então colocamos o id dessas variaveis no map, caso ja exista, retornar um erro de id duplicado
	 *  Ao percorrer a lista, adicionar no mapa a variavel e o seu tipo declarado
	 */
	def checkDeclaracaoVariavel(variableDeclaration vd) {
		var declaracoes = vd.identifierList.identifierList1;
		var declaracaoUnica = vd.identifierList.identifier;

		if (!declaracoes.isNullOrEmpty()) {
			for (identifier id : declaracoes) {
				if (jaDeclarada(id)) {
					error("id variavel duplicado: " + id.identifier, null, id.identifier);
				} else {
					variaveisDeclaradas.put(id.identifier, id);
					variaveisTipo.put(id.identifier, getTypeVar(vd.type));
				}
			}
		}
		if (declaracaoUnica !== null && jaDeclarada(declaracaoUnica)) {
			error("id variavel duplicado: " + declaracaoUnica.identifier, null, declaracaoUnica.identifier);
		} else {
			variaveisDeclaradas.put(declaracaoUnica.identifier, declaracaoUnica);
			variaveisTipo.put(declaracaoUnica.identifier, getTypeVar(vd.type));
		}

	}

	def boolean jaDeclarada(identifier variavel) {
		return (this.variaveisDeclaradas.containsKey(variavel.identifier))
	}

	def String getTypeVar(type tipoVariavel) {

		if (tipoVariavel.simpleType !== null) {
			return getSimpleType(tipoVariavel);
		}
		if (tipoVariavel.structuredType !== null) {
			return getStructuredType(tipoVariavel.structuredType);
		}

		if (tipoVariavel.pointerType !== null) {
			return getPointerType(tipoVariavel.pointerType);
		}
	}

	def getSimpleType(type st) {
		// scalarType   TO-DO: NÃO ENTENDI MUITO BEM COMO FUNCIONA ESSE SCALARTYPE ://
		// subrangeType
		if (st.simpleType.subrangeType !== null) {
			if (st.simpleType.subrangeType.constant !== null && st.simpleType.subrangeType.constant2 !== null) {
				return "range";
			} else {
				error("sao necessarias duas constantes para  intervalo", null);
			}
		}

		// typeIdentifier
		if (st.simpleType.typeIdentifier !== null) {
			if (st.simpleType.typeIdentifier.char !== null) {
				return (st.simpleType.typeIdentifier.char);
			}

			if (st.simpleType.typeIdentifier.boolean !== null) {
				return (st.simpleType.typeIdentifier.boolean);
			}
			if (st.simpleType.typeIdentifier.integer !== null) {
				return (st.simpleType.typeIdentifier.integer);
			}
			if (st.simpleType.typeIdentifier.real !== null) {
				return (st.simpleType.typeIdentifier.real);
			}
			if (st.simpleType.typeIdentifier.string !== null) {
				return (st.simpleType.typeIdentifier.string);
			}

			if (st.simpleType.typeIdentifier.identifier !== null) {
				if (!tiposCriados.contains(st.simpleType.typeIdentifier.identifier.identifier)) {
					error("tipo " + st.simpleType.typeIdentifier.identifier.identifier + " nao existe!", null);
				} else {
					return st.simpleType.typeIdentifier.identifier.identifier;
				}
			// Verificacao pra quando sao criados tipos durante o programa,
			// precisa criar um Map de "tipos criados pra fazer essa verificação					
			}
		}

		if (st.simpleType.stringtype !== null) {
//			return st.stringtype;
		}
	// stringType
	//
	}

	/**
	 * Retonar o tipo "record" da variavel, como na declaracao queremos apenas guardar qual o tipo daquela variavel
	 * será guardado no mapa de declaracao <identifier, "record">
	 */
	def String getStructuredType(structuredType type) {
		// Record eh structured type, nao sei seprecisaria verificar array, set, etc... 
		var unpackeds = type.unpackedStructuredType1;
		if (!unpackeds.isNullOrEmpty()) {
			for (unpackedStructuredType t : unpackeds) {
				var possivelRecord = t.recordType;

				if (possivelRecord !== null) {
					return "record";
				}
			}
		}
	}

	def String getPointerType(pointerType type) {
		if (type.pointerType !== null) {
			return "^"
		}
	}

	/**
	 * variableDeclarationPart: Pode ter varias declaracoes: 
	 * 		Ex: var....; var ....;
	 * Se for so uma, chama o metodo que verifica a declaracao
	 * Se for uma lista, fazer um for na mesma e chamar o metodo que verifica a declaracao pra cada uma
	 */
	@Check
	def checkDeclaracao(variableDeclarationPart decla) {
		var declaracaoUmaVar = decla.variableDeclaration;
		var listaDeclaracoes = decla.variableDeclaration1;

		if (declaracaoUmaVar !== null) {
			checkDeclaracaoVariavel(declaracaoUmaVar);
		}

		if (!listaDeclaracoes.isNullOrEmpty()) {
			for (variableDeclaration declaracao : listaDeclaracoes) {
				checkDeclaracaoVariavel(declaracao);
			}
		}

	}

	@Check
	def checkTypeCase(caseStatement caseStatement) {
		var String tipoExpressionCase;
		var factor fac = caseStatement.expression.simpleExpression.term.signedFactor.factor;
		var unsignedConstant unsConst;
		var unsignedNumber unsNumb;
		var variable vari;

		// Caso em que a exp do case eh uma variavel
		var expVariavel = caseStatement.expression.simpleExpression.term.signedFactor.factor.variable.identifier.
			identifier;

		if (expVariavel !== null) {
			if(variaveisDeclaradas.containsKey(expVariavel)){
				tipoExpressionCase = variaveisTipo.get(expVariavel);	
			}else{
				error("variavel " + expVariavel + " nao declarada", null);
			}
			
		}



		if (fac.unsignedConstant !== null) {
			if (fac.unsignedConstant.unsignedNumber !== null) {
				unsNumb = unsConst.unsignedNumber;

				if (unsNumb.unsignedInteger !== null) {
//					tipoCase = "integer";
				}

				if (unsNumb.unsignedReal !== null) {
//					tipoCase = "real";
				}
			}

			if (unsConst.string_literal !== null) {
				return unsConst.string_literal;
			}

			if (unsConst.constantChr !== null) {
				return unsConst.constantChr.unsignedInteger.number;
			}
		}

		if (fac.bool !== null) {
			return fac.bool
		}

		if (fac.functionDesignator !== null) {
		}

		if (fac.variable !== null) {
			vari = caseStatement.expression.simpleExpression.term.signedFactor.factor.variable;
			if (vari.identifier !== null) {
				return vari.identifier.identifier;
			}
		}
	}

	def checkCompoundStatement(compoundStatement cs) {
		var blocos = cs.statements.statement;
		for (statement st : blocos) {
			var nome = st.unlabelledStatement
			// simpleStatement -- Fazer
			// structuredStatement
			if (nome.structuredStatement !== null) {
				var possivelCase = nome.structuredStatement.conditionalStatement
				if (possivelCase !== null && possivelCase.caseStatement !== null) {
					checkTypeCase(possivelCase.caseStatement);
				}
			}
		// identifier (Eu acho que era procedureStatement)
		}

	}

	@Check
	def runChecks(block b) {
//		var declaracoes = b.variableDeclarationParts;
//		for (variableDeclarationPart e : declaracoes) {
//			checkDeclaracao(e);
//		}
	}
}
