/**
 * generated by Xtext 2.15.0
 */
package compilador.validation;

import compilador.pascal.caseStatement;
import compilador.validation.AbstractPascalValidator;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PascalValidator extends AbstractPascalValidator {
  @Check
  public Object checkCaseStatement(final caseStatement cs) {
    return null;
  }
}
