/**
 * generated by Xtext 2.15.0
 */
package compilador.pascal.impl;

import compilador.pascal.PascalPackage;
import compilador.pascal.identifier;
import compilador.pascal.parameterList;
import compilador.pascal.simpleStatement;
import compilador.pascal.structuredStatement;
import compilador.pascal.unlabelledStatement;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>unlabelled Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link compilador.pascal.impl.unlabelledStatementImpl#getSimpleStatement <em>Simple Statement</em>}</li>
 *   <li>{@link compilador.pascal.impl.unlabelledStatementImpl#getStructuredStatement <em>Structured Statement</em>}</li>
 *   <li>{@link compilador.pascal.impl.unlabelledStatementImpl#getIdentifier <em>Identifier</em>}</li>
 *   <li>{@link compilador.pascal.impl.unlabelledStatementImpl#getParameterList <em>Parameter List</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class unlabelledStatementImpl extends MinimalEObjectImpl.Container implements unlabelledStatement
{
  /**
   * The cached value of the '{@link #getSimpleStatement() <em>Simple Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimpleStatement()
   * @generated
   * @ordered
   */
  protected simpleStatement simpleStatement;

  /**
   * The cached value of the '{@link #getStructuredStatement() <em>Structured Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStructuredStatement()
   * @generated
   * @ordered
   */
  protected structuredStatement structuredStatement;

  /**
   * The cached value of the '{@link #getIdentifier() <em>Identifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdentifier()
   * @generated
   * @ordered
   */
  protected identifier identifier;

  /**
   * The cached value of the '{@link #getParameterList() <em>Parameter List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameterList()
   * @generated
   * @ordered
   */
  protected parameterList parameterList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected unlabelledStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.UNLABELLED_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public simpleStatement getSimpleStatement()
  {
    return simpleStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSimpleStatement(simpleStatement newSimpleStatement, NotificationChain msgs)
  {
    simpleStatement oldSimpleStatement = simpleStatement;
    simpleStatement = newSimpleStatement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.UNLABELLED_STATEMENT__SIMPLE_STATEMENT, oldSimpleStatement, newSimpleStatement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSimpleStatement(simpleStatement newSimpleStatement)
  {
    if (newSimpleStatement != simpleStatement)
    {
      NotificationChain msgs = null;
      if (simpleStatement != null)
        msgs = ((InternalEObject)simpleStatement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.UNLABELLED_STATEMENT__SIMPLE_STATEMENT, null, msgs);
      if (newSimpleStatement != null)
        msgs = ((InternalEObject)newSimpleStatement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.UNLABELLED_STATEMENT__SIMPLE_STATEMENT, null, msgs);
      msgs = basicSetSimpleStatement(newSimpleStatement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.UNLABELLED_STATEMENT__SIMPLE_STATEMENT, newSimpleStatement, newSimpleStatement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public structuredStatement getStructuredStatement()
  {
    return structuredStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStructuredStatement(structuredStatement newStructuredStatement, NotificationChain msgs)
  {
    structuredStatement oldStructuredStatement = structuredStatement;
    structuredStatement = newStructuredStatement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.UNLABELLED_STATEMENT__STRUCTURED_STATEMENT, oldStructuredStatement, newStructuredStatement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStructuredStatement(structuredStatement newStructuredStatement)
  {
    if (newStructuredStatement != structuredStatement)
    {
      NotificationChain msgs = null;
      if (structuredStatement != null)
        msgs = ((InternalEObject)structuredStatement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.UNLABELLED_STATEMENT__STRUCTURED_STATEMENT, null, msgs);
      if (newStructuredStatement != null)
        msgs = ((InternalEObject)newStructuredStatement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.UNLABELLED_STATEMENT__STRUCTURED_STATEMENT, null, msgs);
      msgs = basicSetStructuredStatement(newStructuredStatement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.UNLABELLED_STATEMENT__STRUCTURED_STATEMENT, newStructuredStatement, newStructuredStatement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public identifier getIdentifier()
  {
    return identifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIdentifier(identifier newIdentifier, NotificationChain msgs)
  {
    identifier oldIdentifier = identifier;
    identifier = newIdentifier;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.UNLABELLED_STATEMENT__IDENTIFIER, oldIdentifier, newIdentifier);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdentifier(identifier newIdentifier)
  {
    if (newIdentifier != identifier)
    {
      NotificationChain msgs = null;
      if (identifier != null)
        msgs = ((InternalEObject)identifier).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.UNLABELLED_STATEMENT__IDENTIFIER, null, msgs);
      if (newIdentifier != null)
        msgs = ((InternalEObject)newIdentifier).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.UNLABELLED_STATEMENT__IDENTIFIER, null, msgs);
      msgs = basicSetIdentifier(newIdentifier, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.UNLABELLED_STATEMENT__IDENTIFIER, newIdentifier, newIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public parameterList getParameterList()
  {
    return parameterList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParameterList(parameterList newParameterList, NotificationChain msgs)
  {
    parameterList oldParameterList = parameterList;
    parameterList = newParameterList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.UNLABELLED_STATEMENT__PARAMETER_LIST, oldParameterList, newParameterList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParameterList(parameterList newParameterList)
  {
    if (newParameterList != parameterList)
    {
      NotificationChain msgs = null;
      if (parameterList != null)
        msgs = ((InternalEObject)parameterList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.UNLABELLED_STATEMENT__PARAMETER_LIST, null, msgs);
      if (newParameterList != null)
        msgs = ((InternalEObject)newParameterList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.UNLABELLED_STATEMENT__PARAMETER_LIST, null, msgs);
      msgs = basicSetParameterList(newParameterList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.UNLABELLED_STATEMENT__PARAMETER_LIST, newParameterList, newParameterList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PascalPackage.UNLABELLED_STATEMENT__SIMPLE_STATEMENT:
        return basicSetSimpleStatement(null, msgs);
      case PascalPackage.UNLABELLED_STATEMENT__STRUCTURED_STATEMENT:
        return basicSetStructuredStatement(null, msgs);
      case PascalPackage.UNLABELLED_STATEMENT__IDENTIFIER:
        return basicSetIdentifier(null, msgs);
      case PascalPackage.UNLABELLED_STATEMENT__PARAMETER_LIST:
        return basicSetParameterList(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PascalPackage.UNLABELLED_STATEMENT__SIMPLE_STATEMENT:
        return getSimpleStatement();
      case PascalPackage.UNLABELLED_STATEMENT__STRUCTURED_STATEMENT:
        return getStructuredStatement();
      case PascalPackage.UNLABELLED_STATEMENT__IDENTIFIER:
        return getIdentifier();
      case PascalPackage.UNLABELLED_STATEMENT__PARAMETER_LIST:
        return getParameterList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PascalPackage.UNLABELLED_STATEMENT__SIMPLE_STATEMENT:
        setSimpleStatement((simpleStatement)newValue);
        return;
      case PascalPackage.UNLABELLED_STATEMENT__STRUCTURED_STATEMENT:
        setStructuredStatement((structuredStatement)newValue);
        return;
      case PascalPackage.UNLABELLED_STATEMENT__IDENTIFIER:
        setIdentifier((identifier)newValue);
        return;
      case PascalPackage.UNLABELLED_STATEMENT__PARAMETER_LIST:
        setParameterList((parameterList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.UNLABELLED_STATEMENT__SIMPLE_STATEMENT:
        setSimpleStatement((simpleStatement)null);
        return;
      case PascalPackage.UNLABELLED_STATEMENT__STRUCTURED_STATEMENT:
        setStructuredStatement((structuredStatement)null);
        return;
      case PascalPackage.UNLABELLED_STATEMENT__IDENTIFIER:
        setIdentifier((identifier)null);
        return;
      case PascalPackage.UNLABELLED_STATEMENT__PARAMETER_LIST:
        setParameterList((parameterList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.UNLABELLED_STATEMENT__SIMPLE_STATEMENT:
        return simpleStatement != null;
      case PascalPackage.UNLABELLED_STATEMENT__STRUCTURED_STATEMENT:
        return structuredStatement != null;
      case PascalPackage.UNLABELLED_STATEMENT__IDENTIFIER:
        return identifier != null;
      case PascalPackage.UNLABELLED_STATEMENT__PARAMETER_LIST:
        return parameterList != null;
    }
    return super.eIsSet(featureID);
  }

} //unlabelledStatementImpl
