/**
 * generated by Xtext 2.15.0
 */
package compilador.pascal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>actual Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link compilador.pascal.actualParameter#getActualParameter <em>Actual Parameter</em>}</li>
 *   <li>{@link compilador.pascal.actualParameter#getExpression <em>Expression</em>}</li>
 * </ul>
 * </p>
 *
 * @see compilador.pascal.PascalPackage#getactualParameter()
 * @model
 * @generated
 */
public interface actualParameter extends parameterList
{
  /**
   * Returns the value of the '<em><b>Actual Parameter</b></em>' containment reference list.
   * The list contents are of type {@link compilador.pascal.actualParameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actual Parameter</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actual Parameter</em>' containment reference list.
   * @see compilador.pascal.PascalPackage#getactualParameter_ActualParameter()
   * @model containment="true"
   * @generated
   */
  EList<actualParameter> getActualParameter();

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(expression)
   * @see compilador.pascal.PascalPackage#getactualParameter_Expression()
   * @model containment="true"
   * @generated
   */
  expression getExpression();

  /**
   * Sets the value of the '{@link compilador.pascal.actualParameter#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(expression value);

} // actualParameter
