/**
 * generated by Xtext 2.15.0
 */
package compilador.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>constant Definition Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link compilador.pascal.constantDefinitionPart#getConstantDefinition <em>Constant Definition</em>}</li>
 * </ul>
 * </p>
 *
 * @see compilador.pascal.PascalPackage#getconstantDefinitionPart()
 * @model
 * @generated
 */
public interface constantDefinitionPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Constant Definition</b></em>' containment reference list.
   * The list contents are of type {@link compilador.pascal.constantDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constant Definition</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant Definition</em>' containment reference list.
   * @see compilador.pascal.PascalPackage#getconstantDefinitionPart_ConstantDefinition()
   * @model containment="true"
   * @generated
   */
  EList<constantDefinition> getConstantDefinition();

} // constantDefinitionPart
