/**
 * generated by Xtext 2.15.0
 */
package compilador.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>field List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link compilador.pascal.fieldList#getFixedPart <em>Fixed Part</em>}</li>
 *   <li>{@link compilador.pascal.fieldList#getVariantPart <em>Variant Part</em>}</li>
 *   <li>{@link compilador.pascal.fieldList#getVariantPart1 <em>Variant Part1</em>}</li>
 * </ul>
 * </p>
 *
 * @see compilador.pascal.PascalPackage#getfieldList()
 * @model
 * @generated
 */
public interface fieldList extends EObject
{
  /**
   * Returns the value of the '<em><b>Fixed Part</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fixed Part</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fixed Part</em>' containment reference.
   * @see #setFixedPart(fixedPart)
   * @see compilador.pascal.PascalPackage#getfieldList_FixedPart()
   * @model containment="true"
   * @generated
   */
  fixedPart getFixedPart();

  /**
   * Sets the value of the '{@link compilador.pascal.fieldList#getFixedPart <em>Fixed Part</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fixed Part</em>' containment reference.
   * @see #getFixedPart()
   * @generated
   */
  void setFixedPart(fixedPart value);

  /**
   * Returns the value of the '<em><b>Variant Part</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variant Part</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variant Part</em>' containment reference.
   * @see #setVariantPart(variantPart)
   * @see compilador.pascal.PascalPackage#getfieldList_VariantPart()
   * @model containment="true"
   * @generated
   */
  variantPart getVariantPart();

  /**
   * Sets the value of the '{@link compilador.pascal.fieldList#getVariantPart <em>Variant Part</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variant Part</em>' containment reference.
   * @see #getVariantPart()
   * @generated
   */
  void setVariantPart(variantPart value);

  /**
   * Returns the value of the '<em><b>Variant Part1</b></em>' containment reference list.
   * The list contents are of type {@link compilador.pascal.variantPart}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variant Part1</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variant Part1</em>' containment reference list.
   * @see compilador.pascal.PascalPackage#getfieldList_VariantPart1()
   * @model containment="true"
   * @generated
   */
  EList<variantPart> getVariantPart1();

} // fieldList
