/**
 * generated by Xtext 2.16.0
 */
package compilador.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>function Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link compilador.pascal.functionDeclaration#getIdentifier <em>Identifier</em>}</li>
 *   <li>{@link compilador.pascal.functionDeclaration#getFormalParameterList <em>Formal Parameter List</em>}</li>
 *   <li>{@link compilador.pascal.functionDeclaration#getTypeIdentifier <em>Type Identifier</em>}</li>
 *   <li>{@link compilador.pascal.functionDeclaration#getBlock <em>Block</em>}</li>
 * </ul>
 *
 * @see compilador.pascal.PascalPackage#getfunctionDeclaration()
 * @model
 * @generated
 */
public interface functionDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Identifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier</em>' containment reference.
   * @see #setIdentifier(identifier)
   * @see compilador.pascal.PascalPackage#getfunctionDeclaration_Identifier()
   * @model containment="true"
   * @generated
   */
  identifier getIdentifier();

  /**
   * Sets the value of the '{@link compilador.pascal.functionDeclaration#getIdentifier <em>Identifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier</em>' containment reference.
   * @see #getIdentifier()
   * @generated
   */
  void setIdentifier(identifier value);

  /**
   * Returns the value of the '<em><b>Formal Parameter List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Formal Parameter List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formal Parameter List</em>' containment reference.
   * @see #setFormalParameterList(formalParameterList)
   * @see compilador.pascal.PascalPackage#getfunctionDeclaration_FormalParameterList()
   * @model containment="true"
   * @generated
   */
  formalParameterList getFormalParameterList();

  /**
   * Sets the value of the '{@link compilador.pascal.functionDeclaration#getFormalParameterList <em>Formal Parameter List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Formal Parameter List</em>' containment reference.
   * @see #getFormalParameterList()
   * @generated
   */
  void setFormalParameterList(formalParameterList value);

  /**
   * Returns the value of the '<em><b>Type Identifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Identifier</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Identifier</em>' containment reference.
   * @see #setTypeIdentifier(typeIdentifier)
   * @see compilador.pascal.PascalPackage#getfunctionDeclaration_TypeIdentifier()
   * @model containment="true"
   * @generated
   */
  typeIdentifier getTypeIdentifier();

  /**
   * Sets the value of the '{@link compilador.pascal.functionDeclaration#getTypeIdentifier <em>Type Identifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Identifier</em>' containment reference.
   * @see #getTypeIdentifier()
   * @generated
   */
  void setTypeIdentifier(typeIdentifier value);

  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference.
   * @see #setBlock(block)
   * @see compilador.pascal.PascalPackage#getfunctionDeclaration_Block()
   * @model containment="true"
   * @generated
   */
  block getBlock();

  /**
   * Sets the value of the '{@link compilador.pascal.functionDeclaration#getBlock <em>Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block</em>' containment reference.
   * @see #getBlock()
   * @generated
   */
  void setBlock(block value);

} // functionDeclaration
