/**
 * generated by Xtext 2.15.0
 */
package compilador.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>label declaration part</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see compilador.pascal.PascalPackage#getlabel_declaration_part()
 * @model
 * @generated
 */
public interface label_declaration_part extends EObject
{
} // label_declaration_part
