/**
 * generated by Xtext 2.15.0
 */
package compilador.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>procedure And Function Declaration Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link compilador.pascal.procedureAndFunctionDeclarationPart#getProcedureOrFunctionDeclaration <em>Procedure Or Function Declaration</em>}</li>
 * </ul>
 * </p>
 *
 * @see compilador.pascal.PascalPackage#getprocedureAndFunctionDeclarationPart()
 * @model
 * @generated
 */
public interface procedureAndFunctionDeclarationPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Procedure Or Function Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Procedure Or Function Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procedure Or Function Declaration</em>' containment reference.
   * @see #setProcedureOrFunctionDeclaration(procedureOrFunctionDeclaration)
   * @see compilador.pascal.PascalPackage#getprocedureAndFunctionDeclarationPart_ProcedureOrFunctionDeclaration()
   * @model containment="true"
   * @generated
   */
  procedureOrFunctionDeclaration getProcedureOrFunctionDeclaration();

  /**
   * Sets the value of the '{@link compilador.pascal.procedureAndFunctionDeclarationPart#getProcedureOrFunctionDeclaration <em>Procedure Or Function Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Procedure Or Function Declaration</em>' containment reference.
   * @see #getProcedureOrFunctionDeclaration()
   * @generated
   */
  void setProcedureOrFunctionDeclaration(procedureOrFunctionDeclaration value);

} // procedureAndFunctionDeclarationPart
