/**
 * generated by Xtext 2.16.0
 */
package compilador.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>subrange Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link compilador.pascal.subrangeType#getConstant <em>Constant</em>}</li>
 *   <li>{@link compilador.pascal.subrangeType#getConstant2 <em>Constant2</em>}</li>
 * </ul>
 *
 * @see compilador.pascal.PascalPackage#getsubrangeType()
 * @model
 * @generated
 */
public interface subrangeType extends EObject
{
  /**
   * Returns the value of the '<em><b>Constant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constant</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' containment reference.
   * @see #setConstant(constant)
   * @see compilador.pascal.PascalPackage#getsubrangeType_Constant()
   * @model containment="true"
   * @generated
   */
  constant getConstant();

  /**
   * Sets the value of the '{@link compilador.pascal.subrangeType#getConstant <em>Constant</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' containment reference.
   * @see #getConstant()
   * @generated
   */
  void setConstant(constant value);

  /**
   * Returns the value of the '<em><b>Constant2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constant2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant2</em>' containment reference.
   * @see #setConstant2(constant)
   * @see compilador.pascal.PascalPackage#getsubrangeType_Constant2()
   * @model containment="true"
   * @generated
   */
  constant getConstant2();

  /**
   * Sets the value of the '{@link compilador.pascal.subrangeType#getConstant2 <em>Constant2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant2</em>' containment reference.
   * @see #getConstant2()
   * @generated
   */
  void setConstant2(constant value);

} // subrangeType
